/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.AgendamentoController;
import control.FuncionarioController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AgendamentoModel;
import model.FuncionarioModel;

/**
 *
 * @author adeil
 */
public class Tela_Agendamentos extends javax.swing.JPanel {
    AgendamentoController ac = new AgendamentoController();
    FuncionarioController fc = new FuncionarioController();
    AgendamentoModel agendamento = new AgendamentoModel();
    List<FuncionarioModel> funcList = fc.pegarDoBanco();
    /**
     * Creates new form Tela_Agendamentos
     */
    public Tela_Agendamentos() {
        initComponents();
        ac.tblListar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendamentos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnOS = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 250, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 104, 22));
        jLabel2.setText("AGENDAMENTOS");

        tblAgendamentos.setBackground(new java.awt.Color(243, 250, 220));
        tblAgendamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblAgendamentos.setForeground(new java.awt.Color(92, 104, 22));
        tblAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "DATA", "HORA", "RESPONSÁVEL", "SERVIÇO", "PAGAMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgendamentos.setRowHeight(25);
        tblAgendamentos.setRowMargin(5);
        tblAgendamentos.setSelectionBackground(new java.awt.Color(157, 205, 90));
        tblAgendamentos.getTableHeader().setResizingAllowed(false);
        tblAgendamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAgendamentos);
        if (tblAgendamentos.getColumnModel().getColumnCount() > 0) {
            tblAgendamentos.getColumnModel().getColumn(0).setResizable(false);
            tblAgendamentos.getColumnModel().getColumn(1).setResizable(false);
            tblAgendamentos.getColumnModel().getColumn(2).setResizable(false);
            tblAgendamentos.getColumnModel().getColumn(3).setResizable(false);
            tblAgendamentos.getColumnModel().getColumn(4).setResizable(false);
            tblAgendamentos.getColumnModel().getColumn(5).setResizable(false);
            tblAgendamentos.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo (1).png"))); // NOI18N

        jLabel1.setText("Selecione um agendamento para emitir OS*");

        btnOS.setBackground(new java.awt.Color(157, 205, 90));
        btnOS.setText("EMITIR OS");
        btnOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(157, 205, 90));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOSActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int selectedRow = tblAgendamentos.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblAgendamentos.getModel();
        
        if(selectedRow >= 0){
            int opt = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este agendamento?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if(opt == 0) {
                agendamento.setId(Integer.parseInt(model.getValueAt(selectedRow, 0).toString()));
                ac.excluir(agendamento.getId());
                model.removeRow(selectedRow);
                model.fireTableDataChanged();
            }
        
        }
        else {
                JOptionPane.showMessageDialog(null, "Favor selecionar um agendamento pafa editar!!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblAgendamentos;
    // End of variables declaration//GEN-END:variables
}
